### PR TITLE
Remove authorization - not needed, but authorization does need tipoff…

### PR DESCRIPTION
**Pull request by pdbreen**
…/test-support

### CODE REVIEW

**Comment by drewroberts** [comment]
OK, I thought we needed this the other way around. Wouldn't tests be better if we had the user model?

**Comment by pdbreen** [comment]
Tests can either use the `Tipoff\TestSupport\Models\User` - or, if they can include tipoff/authorization, they can use the `Tipoff\Authorization\Models\User`

**Comment by drewroberts** [comment]
OK, I would rather them use the actual user model since we'll be making a lot more changes to that Authorization package and it would be more accurate to run tests with the actual User model in the application.

**Comment by pdbreen** [comment]
Then, you definitely want this change.  As the new auth version is rolled out, packages will need to swap from using the user model in test-support to the one in auth, then we can remove the user model in this package - probably by end of week at latest.

**Comment by drewroberts** [comment]
That makes sense. Thank you!

**Review by drewroberts — APPROVED** [review]
Thanks! 🎪

**Pull request merged**
